CC=gcc
CFLAGS=-Wall -Wpedantic -Wextra -std=gnu17

default:
	make all

all:
	$(CC) -o process_scheduling_simulator process_scheduling_simulator.c $(CFLAGS)

clean:
	rm -f process_scheduling_simulator

